"""Add detailed_log to ScanJobs

Revision ID: 5217575c3dae
Revises: 93cb7801605f
Create Date: 2026-04-07 21:08:07.472442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5217575c3dae'
down_revision: Union[str, Sequence[str], None] = '93cb7801605f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('detailed_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'detailed_log')
    # ### end Alembic commands ###
