"""Add ScanJobs

Revision ID: bbca3cdeedca
Revises: e5fe17f6b836
Create Date: 2026-04-07 19:56:45.161859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbca3cdeedca'
down_revision: Union[str, Sequence[str], None] = 'e5fe17f6b836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
